version: "3"

tasks:
  generate:
    aliases:
      - gen
    desk: "Генерация proto файла"
    cmds:
      - protoc -I proto proto/sso.proto --go_out=./gen --go_opt=paths=source_relative --go-grpc_out=./gen --go-grpc_out=paths=source_relative