version: "3"

tasks:
  generate:
    aliases:
      - gen
    desk: "Генерация proto файла"
    cmds:
        - protoc -I internal/generate/grpc/proto --go_out=internal/generate/grpc/gen --go_opt=paths=source_relative --go-grpc_out=internal/generate/grpc/gen --go-grpc_opt=paths=source_relative internal/generate/grpc/proto/sso.proto
